### ISSUE TITLE
DUI Preview App 개발

### ISSUE THREAD

**Issue by dohyeon43** [Team-B1ND/dui-android#6]
## 개요
DUI 요소들을 손쉽게 볼 수 있는 Preview 어플

## 작업 사항
- **파운데이션 구현**
    - Color
    - Typo
    - Icon
    - Radius
    - 기본적인 시각 규칙
- **코어 컴포넌트**
    - Bar
    - Badge
    - Button
    - Chip
    - 기본 컴포넌트
위 요소들을 모두 보여줘야함

**Comment by snack655** [comment]
도현씨 그거 한 이슈에 담고 하기에는 좀 힘든 면이...
