### ISSUE TITLE
Jitpack 1.0.1 배포 문제

### ISSUE THREAD

**Issue by snack655** [Team-B1ND/dui-android#72]
## 문제 상황
Jitpack 1.0.1이 배포되지 않습니다..

## 원인
https://jitpack.io/com/github/Team-B1ND/dui-android/1.0.1/build.log

## 작업 내용
* 삽질..?

**Comment by jisungbin** [comment]
안녕하세요.
많은 저장소 중에서 jitpack을 선택하신 이유가 있을까요? MavenCentral도 있습니다.

**Comment by snack655** [comment]
안녕하세요!
저도 그 부분에 관해서 고민해 봤는데 
제가 이렇게 라이브러리를 배포해본 경험이 없어서 MavenCentral 보다 상대적으로 쉽다고 하는 Jitpack을 선택하게 됐어요.
